#!/bin/bash
# Setup Hosts                      (c) 2015 University of California, Irvine
# --------------------------------------------------------------------------
# This script is designed to setup DNS (as defined in /etc/hosts) on each
# compute node on the cluster. It is THE central source for any changes that
# should be made to /etc/hosts. Any other changes made outside this script
# WILL BE LOST IF THIS SCRIPT GETS RAN.
#
# The good news is, this script can be re-ran over and over again and not
# break the node. To be clear: okay to run at any point in time, before or 
# after a node has been imaged.
#
# Orginal work based off of Joseph's setup-mounts.sh script. Thanks!!!
#
# @author       Adam Brenner    <aebrenne@uci.edu>, <adam@aeb.io>
# @version      1.0
# @date         12/2014

if [[ `hostname` == "services-xcat" ]];then
    printf "\n -----> Do NOT run this on XCAT Server!   Exiting.\n\n"
    exit -1
fi

HOST=$(hostname -s);
HOSTFILE="/etc/hosts"

echo "--> Working on node [ $HOST ] to setup dns via $HOSTFILE"
echo " "

/bin/cat << EOF > $HOSTFILE
#######################################################################
## J. Farran
## Do NOT edit this file /etc/hosts by hand.   Run 
##
##    /data/xcat/node-setup/setup-hosts.sh
##
## if you need to update the file.
#######################################################################
127.0.0.1       localhost.localdomain   localhost
128.200.84.225  hpc-s.oit.uci.edu
10.1.1.1        hpc-s.local             hpc-s
`hostname -i | /bin/awk '{print $1}'`    $(hostname)      $(hostname -s)
10.1.255.239    nas-7-7.local           nas-7-7
10.2.255.239    nas-7-7.ib
10.1.255.112    nas-7-4.local           nas-7-4
EOF

# Avoid duplicate /etc/host entries
HOSTALIAS=`hostname -s`
echo  "10.1.254.233    services-7-1.local      services-7-1
10.1.254.196    services-7-2.local      services-7-2" | \
grep -v $HOSTALIAS >> $HOSTFILE

# Test for Infiniband and setup up accordingly
INFINI=''
INFINI=$(/usr/sbin/ibhosts 2>&1 | grep 'hpc-s')

if [ "$INFINI" ];then
    echo "Node has Infiniband [ $HOST ]."

/bin/cat << EOF >> $HOSTFILE

# BeeGFS Filesystems - Infiniband
10.2.255.160    nas-7-1.ib
10.2.255.153    dfm-1-1.ib
10.2.255.139    dfm-2-1.ib

10.2.255.36     dfs-3-1.ib
10.2.254.193    dfs-3-2.ib
10.1.100.102	services-xcat.local services-xcat

# Private filesystems on compute node. These are here to trick automount
# scripts to mount the filesystem over IB or ethernet. In this case we are
# mounting it via IB.
10.2.255.160    nas-7-1
10.2.255.221    nas-7-2.ib
10.2.255.145    nas-1-1.ib
10.2.255.214    nas-9-1.ib
10.2.255.230    compute-2-1.ib
10.2.255.237    compute-2-2.ib
10.2.255.211    compute-2-13.ib
10.2.255.147    compute-2-17.ib
10.2.255.236    compute-3-1.ib
10.2.255.235    compute-3-2.ib
10.2.255.219    compute-3-3.ib
10.2.255.233    compute-3-4.ib
10.2.255.232    compute-3-5.ib
10.2.255.218    compute-3-6.ib
10.2.255.200    compute-3-7.ib
10.2.255.199    compute-3-8.ib
10.2.255.198    compute-3-9.ib
10.2.255.142    compute-3-10.ib
10.2.255.192    compute-4-7.ib
10.2.255.191    compute-4-8.ib
10.2.255.190    compute-4-9.ib
10.2.255.188    compute-6-1.ib
10.2.255.155    compute-7-11.ib
10.2.255.135    compute-4-13.ib
10.2.255.131    compute-4-15.ib
10.2.255.172    compute-7-1.ib
10.2.255.169    compute-7-3.ib
10.2.255.240    compute-2-8.ib
10.2.255.113    compute-4-26.ib
10.2.254.232    compute-4-29.ib
10.2.255.173    compute-8-17.ib
10.2.255.116    compute-4-24.ib
10.2.255.115    compute-4-25.ib
10.2.255.115    compute-4-25.ib
10.2.255.171    compute-7-2.ib
10.2.255.117    compute-4-43.ib
10.2.254.172    compute-5-15.ib
10.2.254.171    compute-5-16.ib
EOF
else
    echo "Node DOES *NOT* have Infiniband [ $HOST ]." 
   
/bin/cat << EOF >> $HOSTFILE

# BeeGFS Filesystem - MetaData - Ethernet
10.1.255.160    nas-7-1.local              nas-7-1e
10.1.255.153    dfm-1-1.local              dfm-1-1e
10.1.255.139    dfm-2-1.local              dfm-2-1e

10.1.255.36     dfs-3-1.ib
10.1.254.193    dfs-3-2.ib

# Private filesystems on compute node. These are here to trick automount
# scripts to mount the filesystem over IB or ethernet. In this case we are
# mounting it via IB.
10.1.255.160    nas-7-1
10.1.255.221    nas-7-2                     nas-7-2.ib
10.1.255.145    nas-1-1.local               nas-1-1.ib
10.1.255.214    nas-9-1.local               nas-9-1.ib
10.1.255.230    compute-2-1.local           compute-2-1.ib
10.1.255.211    compute-2-13.local          compute-2-13.ib
10.1.255.237    compute-2-2.local           compute-2-2.ib
10.1.255.147    compute-2-17.local          compute-2-17.ib
10.1.255.236    compute-3-1.local           compute-3-1.ib
10.1.255.235    compute-3-2.local           compute-3-2.ib
10.1.255.219    compute-3-3.local           compute-3-3.ib
10.1.255.233    compute-3-4.local           compute-3-4.ib
10.1.255.232    compute-3-5.local           compute-3-5.ib
10.1.255.218    compute-3-6.local           compute-3-6.ib
10.1.255.200    compute-3-7.local           compute-3-7.ib
10.1.255.199    compute-3-8.local           compute-3-8.ib
10.1.255.198    compute-3-9.local           compute-3-9.ib
10.1.255.142    compute-3-10.local          compute-3-10.ib
10.1.255.192    compute-4-7.local           compute-4-7.ib
10.1.255.191    compute-4-8.local           compute-4-8.ib
10.1.255.190    compute-4-9.local           compute-4-9.ib
10.1.255.188    compute-6-1.local           compute-6-1.ib
10.1.255.155    compute-7-11.local          compute-7-11.ib
10.1.255.135    compute-4-13.local          compute-4-13.ib
10.1.255.131    compute-4-15.local          compute-4-15.ib
10.1.255.172    compute-7-1.local           compute-7-1.ib
10.1.255.169    compute-7-3.local           compute-7-3.ib
10.1.255.240    compute-2-8.local           compute-2-8.ib       
10.1.255.113    compute-4-26.local          compute-4-26.ib
10.1.254.232    compute-4-29.local          compute-4-29.ib
10.1.255.173    compute-8-17.local          compute-8-17.ib
10.1.255.116    compute-4-24.local          compute-4-24.ib
10.1.255.115    compute-4-25.local          compute-4-25.ib
10.1.255.171    compute-7-2.local           compute-7-2.ib
10.1.254.249    nas-20-1.local              nas-20-1
10.1.255.117    compute-4-43.local          compute-4-43.ib
10.1.254.172    compute-5-15.local          compute-5-15.ib
10.1.254.171    compute-5-16.local          compute-5-16.ib
EOF
fi

echo " "
echo "--> All done..."
echo " "

exit 0
